version: "3.9"
services:
  app:
    build: .
    env_file: .env
    volumes:
      - appdata:/data           # JSONL logs live here
      - ./app/loads.json:/app/loads.json:ro
    expose:
      - "8080"
  caddy:
    image: caddy:2
    depends_on: [app]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddydata:/data
      - caddyconfig:/config
volumes:
  appdata:
  caddydata:
  caddyconfig:
